// @codekit-prepend 'scripts/sorttable.js'
// @codekit-prepend 'scripts/go_admin_page_admin_user.js'
// @codekit-prepend 'scripts/go_options.js'
// @codekit-prepend 'scripts/go_edit_store.js'
// @codekit-prepend 'scripts/buy_the_item.js'
// @codekit-prepend 'scripts/go_blogs.js'