// @codekit-prepend '/scripts/go_clipboard.js'
// @codekit-prepend '/scripts/sorttable.js'
// @codekit-prepend '/scripts/go_admin_notifications.js'
// @codekit-prepend '/scripts/go_every_admin_page.js'
// @codekit-prepend '/scripts/go_options.js'
// @codekit-prepend '/scripts/go_edit_store.js'